#!/usr/bin/env bash
#
# from Manjaro .bashrc: archive extractor
# usage: ex <file>

if [ ! -f "$1" ] ; then
    printf 'ERROR:Missing file or input.\nUsage: ex <file>\n\n'
    echo "Supported archives:"
    echo "    tar.bz2, tar.gz, tar.xz, bz2, rar, gz, tar, tbz2, tgz, zip, Z, 7z"
    exit 1
fi

case $1 in
    *.tar.bz2)   tar xjf $1   ;;
    *.tar.gz)    tar xzf $1   ;;
    *.tar.xz)    tar xf $1    ;;
    *.bz2)       bunzip2 $1   ;;
    *.rar)       unrar x $1   ;;
    *.gz)        gunzip $1    ;;
    *.tar)       tar xf $1    ;;
    *.tbz2)      tar xjf $1   ;;
    *.tgz)       tar xzf $1   ;;
    *.zip)       unzip $1     ;;
    *.Z)         uncompress $1;;
    *.7z)        7z x $1      ;;
    *)           echo "'$1' cannot be extracted via ex()" ;;
esac
