#!/usr/bin/bash

file="$1"
hash="$2"
algorithm=${3:-256}

# check for missing information
if [ -z "$file" ] || [ -z "$hash" ]; then
  printf "Missing FILENAME or HASH. Please provide.\n"
  printf "Usage: shacheck FILE HASH ALGO=256\n"
  exit 1
fi

echo "$hash *$file" | shasum -a "$algorithm" --check
