#!/usr/bin/env bash

# Taken from https://github.com/ThePrimeagen/.dotfiles/master/bin/.local/scripts/tmux-sessionizer
# Get directories to check (via input or as already defined),
# and create a new session in tmux with the selected directory.

if [ "$#" -gt 1 ]; then
    printf "Too many arguments. Exit."
    exit 1
elif [ "$#" -eq 1 ]; then
    selected="$1"
else
    # select custom directories and choose via fzf
    selected=$(find ~/ ~/Desktop ~/Downloads ~/Documents ~/Documents/ifm-projects ~/.config -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [ -z "$selected" ]; then
    printf "No directories choosen. Exit."
    exit 0
fi

# choose te basename as the session name
# Rename hidden folders to not confuse tmux
session_name=$(basename "$selected" | tr . _)

if [ -z "$TMUX" ] && [ -z "$(pgrep tmux)" ]; then
    # if tmux is not running, open tmux and create new session with name
    # and chosen directory
    tmux new-session -s "$session_name" -c "$selected" &
    exit 0
fi

if ! tmux has-session -t="$session_name" 2> /dev/null; then
    # if no session exists with the selected name, create a new session with
    # the selected name and chosen directory
    tmux new-session -ds "$session_name" -c "$selected"
fi
# else switch to this session
tmux switch-client -t "$session_name"
