#!/usr/bin/env bash
# Jump to window or session depending on input. We are lazy, so just find the
# closest match and jump to that.
#
# To decide if we wan't to jump to a session or window check the first char if
# that is a whitespace. If it is, jump to a window, else to a session.
# Example input:
#  ' foo' -> Jump to window which includes substring foo
#  'bar' -> Jump to session which includes substring bar
#

input="$1"
if [ -z "${input}" ]; then
    echo "Error: No search word found. Please provide." >&2
    exit 0
fi

# Check first char and decide if the target is a window or session.
if [ "${input:0:1}" == ' ' ]; then
  WINDOW=1; type="window"
else
  SESSION=1; type="session"
fi

# Remove whitespace for search
search_word="$(echo "${input}" | tr -d ' ')"
found=""

# Needs to be in format: session
(( SESSION )) &&\
  found="$(tmux ls -F "#S" | grep -i "${search_word}" | head -n 1)"

# Needs to be in format: session:window_index
((WINDOW)) &&\
  found="$(tmux lsw -a -F '#S:#I #W' |\
  awk -v w="${search_word}" '$2 ~ w {print $1; exit}')"

if [ -z "${found}" ]; then
  tmux display-message "No ${type} found with abbreviation '${search_word}'."
  exit 0
fi

tmux switch-client -t "${found}"
