#!/usr/bin/env bash

SESSION=0
WINDOW=0

while getopts "sw" arg; do
  case $arg in
    w)
       WINDOW=1
       ;;
    s)
       SESSION=1
       ;;
    *)
      echo "Invalid argument '${arg}'" >&2
      exit 1
      ;;
  esac
done

if [ $SESSION == $WINDOW ]; then
    echo "Error: -w and -s can't be used together" >&2
    exit 1
fi

# Since $1 is the flag check search word after that
# Search word is at most a single word
search_word="$2"
if [ -z "${search_word}" ]; then
    echo "Error: No search word found. Please provide." >&2
    exit 1
fi

## Search for instance
found=""

# Needs to be in format: session
(( SESSION )) &&\
  found="$(tmux ls -F "#S" | grep -i "${search_word}" | head -n 1)"

# Needs to be in format: session:window_index
((WINDOW)) &&\
  found="$(tmux lsw -a -F '#S:#I #W' |\
  awk -v w="${search_word}" '$2 ~ w {print $1; exit}')"

tmux switch-client -t "${found}"
